import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { getDictionary } from "@/i18n/dictionaries";

export const metadata: Metadata = {
  title: "Terms of Use — Lorescape",
  description:
    "The rules and conditions that govern your use of the Lorescape app and services.",
};

export default function TermsPage() {
  const d = getDictionary("en");
  return (
    <>
      <Navbar d={d} homeHref="/en" />
      <main className="bg-paper pt-32 pb-24 px-6">
        <article
          className="
            max-w-3xl mx-auto text-ink-2 leading-relaxed
            [&_h2]:text-2xl [&_h2]:md:text-3xl [&_h2]:font-serif [&_h2]:font-bold [&_h2]:text-ink
            [&_h2]:tracking-wide [&_h2]:mt-12 [&_h2]:mb-4
            [&_p]:mb-4
            [&_ul]:mb-4 [&_ul]:space-y-2
            [&_ul>li]:list-disc [&_ul>li]:ml-6
            [&_strong]:text-ink [&_strong]:font-semibold
            [&_a]:text-clay [&_a]:underline [&_a]:underline-offset-2 hover:[&_a]:text-clay-deep
          "
        >
          <header className="mb-10">
            <h1 className="text-4xl md:text-5xl font-serif font-bold tracking-wide text-ink mb-3">
              Terms of Use
            </h1>
            <p className="text-sm uppercase tracking-widest text-ink-3">
              Effective Date: 2026-04-23
            </p>
          </header>

          <h2>1. Acceptance of Terms</h2>
          <p>
            Welcome to <strong>Lorescape</strong> (&quot;the App,&quot;
            &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). These Terms of
            Use (&quot;Terms&quot;) are a legally binding agreement between you
            and Lorescape governing your access to and use of the App and
            related services (collectively, the &quot;Service&quot;). By
            downloading, installing, or using the App, you agree to be bound by
            these Terms. If you do not agree, do not use the Service.
          </p>

          <h2>2. The Service</h2>
          <p>
            Lorescape is an AI-powered audio tour guide that generates
            historical and cultural narration based on your location. Content
            is produced in real time using third-party AI services (e.g.,
            Google Gemini) and may include text, audio, and imagery related to
            nearby points of interest.
          </p>

          <h2>3. Eligibility</h2>
          <p>
            You must be at least 13 years old to use the Service. If you are
            between 13 and the age of majority in your jurisdiction, you
            represent that you have your parent or legal guardian&apos;s
            permission to use the Service.
          </p>

          <h2>4. Account</h2>
          <p>
            Some features require you to create an account by signing in with
            a supported identity provider (e.g., Apple, Google). You are
            responsible for:
          </p>
          <ul>
            <li>Maintaining the confidentiality of your account credentials.</li>
            <li>All activity that occurs under your account.</li>
            <li>Promptly notifying us of any unauthorized access.</li>
          </ul>

          <h2>5. Subscriptions &amp; In-App Purchases</h2>
          <p>
            The Service may offer paid subscription tiers or one-time
            purchases (&quot;Purchases&quot;) that unlock additional features.
          </p>
          <ul>
            <li>
              <strong>Billing</strong>: Purchases are processed by Apple App
              Store or Google Play, not Lorescape. All charges are subject to
              the applicable platform&apos;s billing terms.
            </li>
            <li>
              <strong>Auto-Renewal</strong>: Subscriptions automatically renew
              unless canceled at least 24 hours before the end of the current
              period. You can manage or cancel through your App Store /
              Play Store account settings.
            </li>
            <li>
              <strong>Free Trials</strong>: If a free trial is offered, you
              will not be charged during the trial; if you do not cancel
              before the trial ends, you will be charged for the subscription.
            </li>
            <li>
              <strong>Refunds</strong>: Refund requests are handled by Apple
              or Google per their policies. We generally cannot issue refunds
              directly.
            </li>
            <li>
              <strong>Price Changes</strong>: We may change subscription
              prices. Any change will apply to future billing periods only,
              and you will be notified in advance.
            </li>
          </ul>

          <h2>6. AI-Generated Content Disclaimer</h2>
          <p>
            Narration, summaries, and other outputs produced by the Service
            are generated by AI models and may contain inaccuracies,
            omissions, or outdated information.{" "}
            <strong>
              Lorescape does not guarantee the accuracy, completeness, or
              reliability of AI-generated content.
            </strong>{" "}
            Do not rely on the Service for professional, academic, medical,
            legal, or safety-critical advice. Always verify important
            information from authoritative sources.
          </p>

          <h2>7. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>
              Use the Service for unlawful purposes or in violation of any
              applicable law.
            </li>
            <li>
              Reverse engineer, decompile, or attempt to extract source code
              from the App.
            </li>
            <li>
              Scrape, bulk-download, or resell content generated by the
              Service.
            </li>
            <li>
              Upload content that infringes others&apos; rights, contains
              malware, or is otherwise harmful.
            </li>
            <li>
              Attempt to gain unauthorized access to our systems or other
              users&apos; accounts.
            </li>
            <li>Use the Service to harass, abuse, or harm another person.</li>
          </ul>

          <h2>8. Intellectual Property</h2>
          <ul>
            <li>
              <strong>Our IP</strong>: The App, its code, branding, interface,
              and original content are owned by Lorescape and protected by
              copyright, trademark, and other laws.
            </li>
            <li>
              <strong>AI Output</strong>: Content generated by AI in response
              to your queries is provided to you for personal, non-commercial
              use. Factual information is not owned by anyone, but the
              specific narration output remains subject to these Terms.
            </li>
            <li>
              <strong>Your Content</strong>: You retain ownership of any
              content you submit (e.g., feedback). By submitting it, you
              grant us a non-exclusive, worldwide, royalty-free license to
              use it to operate and improve the Service.
            </li>
          </ul>

          <h2>9. Third-Party Services</h2>
          <p>
            The Service integrates with third-party services including but
            not limited to Apple, Google, Supabase, Google Gemini, and
            RevenueCat. Your use of those services is subject to their own
            terms, and we are not responsible for their practices.
          </p>

          <h2>10. Privacy</h2>
          <p>
            Our collection and use of personal information is described in
            our <a href="/privacy">Privacy Policy</a>, which is incorporated
            into these Terms by reference.
          </p>

          <h2>11. Disclaimers</h2>
          <p>
            THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS
            AVAILABLE,&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
            IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR
            PURPOSE, NON-INFRINGEMENT, OR THAT THE SERVICE WILL BE
            UNINTERRUPTED, ERROR-FREE, OR SECURE.
          </p>

          <h2>12. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, LORESCAPE WILL NOT BE
            LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
            PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS OR DATA, ARISING
            FROM YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY FOR ANY CLAIM
            ARISING FROM OR RELATED TO THE SERVICE WILL NOT EXCEED THE
            AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE EVENT
            GIVING RISE TO THE CLAIM, OR USD $50, WHICHEVER IS GREATER.
          </p>

          <h2>13. Termination</h2>
          <p>
            We may suspend or terminate your access to the Service at any
            time, with or without notice, for any reason, including violation
            of these Terms. You may stop using the Service at any time and
            delete your account via <strong>[Settings]</strong> &gt;{" "}
            <strong>[Delete Account]</strong> in the App.
          </p>

          <h2>14. Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time. Material changes
            will be communicated through the App or by email where
            appropriate. Continued use of the Service after changes take
            effect constitutes acceptance of the revised Terms.
          </p>

          <h2>15. Governing Law</h2>
          <p>
            These Terms are governed by the laws of Taiwan (Republic of
            China), without regard to conflict-of-law principles. Any dispute
            arising out of or relating to these Terms or the Service will be
            subject to the exclusive jurisdiction of the courts of Taipei,
            Taiwan, except where mandatory consumer-protection law in your
            jurisdiction requires otherwise.
          </p>

          <h2>16. Contact</h2>
          <p>If you have questions about these Terms, contact us at:</p>
          <ul>
            <li>
              <strong>Email</strong>:{" "}
              <a href="mailto:easylive1989@gmail.com">
                easylive1989@gmail.com
              </a>
            </li>
          </ul>
        </article>
      </main>
      <Footer d={d} homeHref="/en" />
    </>
  );
}
