"""Download Google Fonts .woff2 files used by the IG card renderer.

Run once to populate backend/src/lorescape_backend/social/card/template/fonts/.
The downloaded files are committed to the repo so card rendering is fully
offline at runtime.

Why every subset matters
------------------------
Google Fonts CSS2 returns *multiple* ``@font-face`` blocks per
(family, style, weight) tuple — one per Unicode-range subset (e.g. Latin,
Latin-Ext, Vietnamese, and many CJK chunks for Noto Serif TC). Keeping only
one subset would leave the renderer without the glyphs for other Unicode
ranges (notably: no Chinese characters for Noto Serif TC).

This script therefore downloads every subset for the configured target
weights and emits a ``fonts.css`` snippet that preserves the original
``unicode-range`` of each block, so the browser can pick the right subset
at render time.

Usage:
    cd backend && uv run python scripts/download_card_fonts.py
"""
from __future__ import annotations

import logging
import re
from pathlib import Path

import requests

# Google Fonts CSS2 endpoint returns @font-face blocks pointing at .woff2 URLs.
# Using a modern UA so it serves .woff2 (not legacy formats).
CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Cormorant+Garamond:ital,wght@1,500"
    "&family=EB+Garamond:ital,wght@0,400;1,400"
    "&family=Noto+Serif+TC:wght@400;500;900"
    "&display=swap"
)
# Chrome UA so Google serves woff2 for every subset (Safari UA returns
# legacy .woff for Latin scripts while still serving .woff2 for CJK).
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

FONT_OUT_DIR = (
    Path(__file__).resolve().parent.parent
    / "src" / "lorescape_backend" / "social" / "card" / "template" / "fonts"
)

# (family, style, weight) -> filename PREFIX. The script appends a sequential
# 2-digit suffix to allow many subsets per (family, style, weight) without
# collision: NotoSerifTC-Regular-00.woff2, ...-01.woff2, etc.
FILENAME_PREFIX_MAP: dict[tuple[str, str, str], str] = {
    ("Cormorant Garamond", "italic", "500"): "CormorantGaramond-Italic",
    ("EB Garamond", "normal", "400"):        "EBGaramond-Regular",
    ("EB Garamond", "italic", "400"):        "EBGaramond-Italic",
    ("Noto Serif TC", "normal", "400"):      "NotoSerifTC-Regular",
    ("Noto Serif TC", "normal", "500"):      "NotoSerifTC-Medium",
    ("Noto Serif TC", "normal", "900"):      "NotoSerifTC-Black",
}

FONTS_CSS_HEADER = (
    "/* Auto-generated by scripts/download_card_fonts.py — "
    "do not edit by hand. */\n"
)


def _parse_font_face_blocks(css: str) -> list[dict[str, str | None]]:
    """Parse every ``@font-face`` block in *css* into a list of dicts.

    Each dict contains ``family``, ``style``, ``weight``, ``url`` and
    ``unicode_range`` (the latter may be ``None`` if the block omits it).
    Blocks missing any of the first four fields are skipped.
    """
    blocks: list[dict[str, str | None]] = []
    for block in re.findall(r"@font-face\s*\{([^}]+)\}", css):
        fam = re.search(r"font-family:\s*'([^']+)'", block)
        style = re.search(r"font-style:\s*(\w+)", block)
        weight = re.search(r"font-weight:\s*(\d+)", block)
        url = re.search(r"url\((https://[^)]+)\)\s*format\('woff2'\)", block)
        unicode_range = re.search(r"unicode-range:\s*([^;]+);", block)
        if not (fam and style and weight and url):
            continue
        blocks.append({
            "family": fam.group(1),
            "style": style.group(1),
            "weight": weight.group(1),
            "url": url.group(1),
            "unicode_range": (
                unicode_range.group(1).strip() if unicode_range else None
            ),
        })
    return blocks


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    log = logging.getLogger(__name__)

    FONT_OUT_DIR.mkdir(parents=True, exist_ok=True)

    resp = requests.get(CSS_URL, headers={"User-Agent": UA}, timeout=30)
    resp.raise_for_status()
    css = resp.text

    blocks = _parse_font_face_blocks(css)
    log.info("parsed %d @font-face blocks from CSS", len(blocks))

    # Sequential index per (family, style, weight) target key.
    next_idx: dict[tuple[str, str, str], int] = {}
    # How many subsets each target key actually produced, for the final guard.
    written_by_key: dict[tuple[str, str, str], int] = {
        k: 0 for k in FILENAME_PREFIX_MAP
    }

    fonts_css_lines: list[str] = [FONTS_CSS_HEADER]
    for b in blocks:
        family = b["family"]
        style = b["style"]
        weight = b["weight"]
        url = b["url"]
        assert family and style and weight and url
        key = (family, style, weight)
        prefix = FILENAME_PREFIX_MAP.get(key)
        if not prefix:
            continue
        idx = next_idx.get(key, 0)
        next_idx[key] = idx + 1
        target_name = f"{prefix}-{idx:02d}.woff2"
        target = FONT_OUT_DIR / target_name
        if target.exists():
            log.info("skip   %s (already present)", target_name)
        else:
            log.info("fetch  %s  <- %s", target_name, url)
            font_resp = requests.get(
                url, headers={"User-Agent": UA}, timeout=60,
            )
            font_resp.raise_for_status()
            target.write_bytes(font_resp.content)
        written_by_key[key] += 1

        ur = b["unicode_range"]
        ur_line = f"\n  unicode-range: {ur};" if ur else ""
        fonts_css_lines.append(
            f"@font-face {{\n"
            f"  font-family: '{family}';\n"
            f"  font-style: {style};\n"
            f"  font-weight: {weight};\n"
            f"  font-display: block;\n"
            f"  src: url('./{target_name}') format('woff2');"
            f"{ur_line}\n"
            f"}}\n"
        )

    missing = [k for k, n in written_by_key.items() if n == 0]
    if missing:
        raise SystemExit(f"No subsets fetched for: {missing!r}")

    (FONT_OUT_DIR / "fonts.css").write_text(
        "\n".join(fonts_css_lines), encoding="utf-8",
    )
    log.info(
        "\nWrote %d font files + fonts.css to %s",
        sum(written_by_key.values()),
        FONT_OUT_DIR,
    )


if __name__ == "__main__":
    main()
