import React from "react";
import { AbsoluteFill, useCurrentFrame, interpolate } from "remotion";
import { easeOutExpo } from "../utils/animations";

// Abstract stone surface with golden cracks emerging.
// All visuals are generated by SVG filters + gradients — no external images.
export const StoneTexture: React.FC = () => {
  const frame = useCurrentFrame();

  const crackProgress = interpolate(frame, [15, 90], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: easeOutExpo,
  });

  const glowOpacity = interpolate(frame, [30, 110, 150], [0, 0.9, 0.7], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  const dustDrift = interpolate(frame, [0, 150], [0, 25], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  return (
    <AbsoluteFill>
      {/* Base gradient */}
      <AbsoluteFill
        style={{
          background:
            "radial-gradient(circle at 50% 55%, #1a2230 0%, #0a0f17 55%, #05080d 100%)",
        }}
      />

      {/* Stone noise texture */}
      <svg
        width="100%"
        height="100%"
        style={{ position: "absolute", inset: 0, opacity: 0.55 }}
      >
        <defs>
          <filter id="stoneNoise">
            <feTurbulence
              type="fractalNoise"
              baseFrequency="0.9"
              numOctaves="3"
              seed="7"
            />
            <feColorMatrix
              values="0 0 0 0 0.18  0 0 0 0 0.16  0 0 0 0 0.14  0 0 0 0.8 0"
            />
          </filter>
          <filter id="coarseNoise">
            <feTurbulence
              type="fractalNoise"
              baseFrequency="0.012"
              numOctaves="2"
              seed="4"
            />
            <feDisplacementMap in="SourceGraphic" scale="40" />
          </filter>
        </defs>
        <rect width="100%" height="100%" filter="url(#stoneNoise)" />
      </svg>

      {/* Golden crack path — revealed as crackProgress grows */}
      <svg
        width="100%"
        height="100%"
        viewBox="0 0 1920 1080"
        preserveAspectRatio="none"
        style={{ position: "absolute", inset: 0 }}
      >
        <defs>
          <linearGradient id="crackGrad" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor="#FFC36A" stopOpacity="0.95" />
            <stop offset="50%" stopColor="#FFA93D" stopOpacity="1" />
            <stop offset="100%" stopColor="#FFC36A" stopOpacity="0.5" />
          </linearGradient>
          <filter id="glow" x="-50%" y="-50%" width="200%" height="200%">
            <feGaussianBlur stdDeviation="12" />
          </filter>
        </defs>

        {/* Blurred crack glow */}
        <g filter="url(#glow)" opacity={glowOpacity}>
          <path
            d="M 80 540 L 340 480 L 620 620 L 900 520 L 1180 660 L 1500 500 L 1840 600"
            stroke="url(#crackGrad)"
            strokeWidth={28}
            strokeLinecap="round"
            fill="none"
            pathLength={1}
            strokeDasharray={1}
            strokeDashoffset={1 - crackProgress}
          />
        </g>

        {/* Sharp crack line */}
        <path
          d="M 80 540 L 340 480 L 620 620 L 900 520 L 1180 660 L 1500 500 L 1840 600"
          stroke="url(#crackGrad)"
          strokeWidth={3.5}
          strokeLinecap="round"
          fill="none"
          pathLength={1}
          strokeDasharray={1}
          strokeDashoffset={1 - crackProgress}
        />

        {/* Secondary cracks branching */}
        <g opacity={crackProgress * 0.7}>
          <path
            d="M 620 620 L 740 780 L 820 960"
            stroke="url(#crackGrad)"
            strokeWidth={2}
            fill="none"
            pathLength={1}
            strokeDasharray={1}
            strokeDashoffset={1 - crackProgress}
          />
          <path
            d="M 1180 660 L 1100 830 L 1240 1000"
            stroke="url(#crackGrad)"
            strokeWidth={2}
            fill="none"
            pathLength={1}
            strokeDasharray={1}
            strokeDashoffset={1 - crackProgress}
          />
        </g>
      </svg>

      {/* Central warm glow behind text */}
      <AbsoluteFill
        style={{
          background: `radial-gradient(circle at 50% 55%, rgba(255,178,92,${0.28 * glowOpacity}) 0%, rgba(255,140,40,${0.08 * glowOpacity}) 30%, transparent 60%)`,
          mixBlendMode: "screen",
        }}
      />

      {/* Dust particles drifting upward */}
      <svg
        width="100%"
        height="100%"
        style={{ position: "absolute", inset: 0, opacity: 0.45 }}
      >
        {Array.from({ length: 35 }).map((_, i) => {
          const x = (i * 83) % 1920;
          const y = ((i * 127) % 1080) - dustDrift * (1 + (i % 3));
          const r = 1 + (i % 3) * 0.6;
          return (
            <circle
              key={i}
              cx={x}
              cy={y}
              r={r}
              fill="#ffd59a"
              opacity={0.3 + ((i * 17) % 40) / 100}
            />
          );
        })}
      </svg>

      {/* Subtle vignette */}
      <AbsoluteFill
        style={{
          background:
            "radial-gradient(circle at 50% 50%, transparent 50%, rgba(0,0,0,0.55) 100%)",
        }}
      />
    </AbsoluteFill>
  );
};
